nscaledev/uni-identity

charts/identity/Chart.yaml, pkg/oauth2/federated.go
It's part of the spec, so we should add this in, just in case a library does check it!
=> Add Nonce to OIDC ID Token

README.md
On reading your readme file in the projects section I've spotted it looks like you meant project here, rather than group.
=> Fix typo group -> project in readme

charts/identity/templates/certificate.yaml, charts/identity/templates/clusterrole.yaml, charts/identity/templates/deployment.yaml, charts/identity/values.yaml, go.mod, pkg/authorization/authenticator.go, pkg/handler/handler.go, pkg/jose/jwe.go, pkg/jose/jwe_test.go, pkg/middleware/openapi/local/authorizer.go, pkg/oauth2/accesstoken.go, pkg/oauth2/federated.go, pkg/server/server.go
THe problem we are solving here is currently a token may be issued right before the key pair is rotated, so be comes invalid almost immediately. This will become more troublesome down the line with automation requiring long lived keys (i.e. refresh tokens).  A solution is to create keys that last for 2N, and rotate every N, so any token issued just before a rotation will work for a time of N.  To pull this off we need to create copies of the current keypair and the previous for verification purposes and rotation detection.
=> Issuer Key Rotation

pkg/oauth2/oauth2.go, pkg/oauth2/oauth2_test.go, pkg/oauth2/tokens.go
We need to have a token lifetime of less than the wrapped token to avoid races and avoidable errors that interupt the flow of things.
=> Tweak Token Issue

specifications/resource-metdata.md
Unify metadata handling across all resource types for all APIs in order to make clients simpler to implment and foster code reuse.  Also abstract away things like names, which is the real pain point here.
=> Add API Metadata Specification

README.md, specifications/resource-metdata.md
In lieu of having schemas in place, we need to update the docs to hint that providers and stuff need to have an ID now.
=> Fix Documentation

charts/identity/Chart.yaml, pkg/client/client.go
The OIDC authorizer in core and the identity client need the same options, so lets just share them for now.  Ideally the core library should consume the identity options, but again circular deps hell, so just allow them to be copied over.
=> Temporarily Expose Client Options

pkg/oauth2/oauth2.go, pkg/oauth2/providers/google/provider.go, pkg/oauth2/providers/interfaces.go, pkg/oauth2/providers/null.go
Login in Entra is causing the request size to be blown due to large tokens, probably hinting they encode permissions in there rather thand doing a DB lookup.  As a quick hack, remove the tokens from the code and our tokens to reduce the size, as they aren't necessary.  A long term solution will be to save these details in a DB and pass around much smaller identifiers to allow a lookup.  We need the DB anyway for access token single use and revocaction.
=> Work Around Request Size

charts/identity/Chart.yaml, charts/identity/templates/identity/deployment.yaml
Identity's requests are far too high and prevent scheduling on relatively constrained platforms.
=> Lower Memory Requests

charts/identity/Chart.yaml, charts/identity/crds/identity.unikorn-cloud.org_roles.yaml, pkg/apis/unikorn/v1alpha1/types.go, pkg/handler/handler.go, pkg/handler/roles/client.go, pkg/oauth2/oauth2.go, pkg/rbac/handler.go
So bloody simple when you think about it!  When reading roles, only return the ones you already have all the permissions for at the same or greated scope.  Basically reuses the existing functions like magic!
=> Fix Role RBAC

charts/identity/Chart.yaml, pkg/handler/groups/client.go, pkg/handler/organizations/client.go, pkg/handler/projects/client.go
Ensure API users (you know who), don't taint the system with erroneous inputs and render it unusable, as this stuff will render RBAC doomed.
=> Basic Taint Checking

charts/identity/Chart.yaml, charts/identity/values.yaml
After playing with the UI, it semms quite apparent that mapping a region ID to a name, when the region is itself project scoped is quite heavy weight and unwieldy.  To remedy this we move regions back to the organization scope so we need only a single lookup, relying on RBAC information to do any filtering.  This also splits up regions and instrastructure so readers can map to regions, but not create identities etc.
=> Make Regions Organization Scoped

charts/identity/Chart.yaml, go.mod, go.sum, pkg/oauth2/oauth2.go
When restarting your laptop, it need to re-establish wifi, and during that period any refresh token requests will fail as DNS is down.  Wrap the initial OIDC service discovery in a retry to attempt to ride out the storm.
=> Fix Spurious Logouts

README.md, charts/identity/Chart.yaml, charts/identity/values.yaml, go.mod, go.sum, pkg/handler/groups/client.go, pkg/handler/oauth2providers/client.go, pkg/handler/organizations/client.go, pkg/handler/projects/client.go
Reduce priviliges for services that require access to identities and physical networks.  These need to be read, to extract readiness and provider specific information, and deleted for cluster cleanup. Additionally add in a new endpoint for fine grain API control of the region service.
=> Tighten Up Service Roles

charts/identity/Chart.yaml, pkg/middleware/openapi/remote/authorizer.go, pkg/oauth2/oauth2.go, pkg/oauth2/oauth2_test.go, pkg/oauth2/tokens.go
Transpires that validating tokens is very expensive, so add a cache to identity to speed this up.
=> Add Token Caching

charts/identity/Chart.yaml, pkg/jose/jose.go
Rather than just check the signature against all keys, some libraries expect only a single key for a signature type.  Obviously due to key rotation we maintain multiple, so we need to add the key ID to the token to disabiguate, because a loop just isn't simple enough...
=> Add Key ID to ID Tokens

charts/identity/Chart.yaml, charts/identity/values.yaml, pkg/jose/jose.go
So according to the node jwks stuff, it requires a single candidate key, and it doesn't match on the embedded key at all, just the KID, so we need to inject this into the headers to disambiguate.
=> Second Attempt at Key IDs

pkg/handler/handler.go, pkg/jose/jose.go
The initial idea was to use the key ID to lookup the correct key when verifying and descrypting, but that led to the realization that you can use a JWK rather than a crypto key everywhere, and that leads to the eky ID being populated coreectly, so it's an all around win!
=> Refactor JOSE

charts/identity/Chart.yaml, charts/identity/values.yaml
We need RBAC protection on the applications endpoint that allows the read of platform defined applications, and applicationsets that allow the actual creation of applications onto Kubernetes clusters... I say that because we could possibly define Ansible applications in future for use on general compute.
=> Create RBAC For Applications

charts/identity/Chart.yaml, charts/identity/values.yaml
This pull request introduces RBAC for the following endpoints: computeclusters, servers, and securitygroups to ensure users have appropriate access levels based on their roles.
=> Create RBAC for Compute Clusters

charts/identity/Chart.yaml, charts/identity/values.yaml, pkg/client/client.go, pkg/client/interfaces.go, pkg/client/tokenissuer.go, pkg/handler/handler.go, pkg/handler/organizations/client.go, pkg/middleware/openapi/accesstoken/context.go, pkg/middleware/openapi/remote/authorizer.go
In the old world, before service accounts, the user needed excess premissions to achieve anything, as the token was propagated around services.  You couldn't have a user that could just provision Kubernetes, they needed to be able to provision identities and physical networks too, the latter is a major concern when it comes to DoS attacks against the platform via the API.
=> Tighten RBAC

charts/identity/Chart.yaml, hack/user_migration.go, pkg/handler/users/client.go, pkg/rbac/rbac.go
Update the user activity when an ACL is generated.  Prevent the API from removing the pending state, this is internal to the system and used to enforce security policies.  Also update the user/group initial setup process.
=> Finish Off Users Upgrade

charts/identity/Chart.yaml, pkg/jose/jose.go, pkg/oauth2/oauth2.go
For the most part it's not relying on user provided query parameters for driving redirects or template rendering.
Fixes #151 and #152
=> Fix CodeQL Warnings

charts/identity/Chart.yaml, pkg/oauth2/oauth2.go, pkg/oauth2/oauth2_test.go, pkg/oauth2/tokens.go
Not done enough testing with non-Google evidently.  This fixes a bunch of issues with providers that don't support refresh tokens.  And also fixes Google that got broken somewhere along the way.
=> Fixes for Refresh Tokens

charts/identity/Chart.yaml, pkg/handler/common/common.go, pkg/handler/organizations/client.go, pkg/handler/quotas/client.go
Elegant upgrade path alert... if an organization quota does not exist, then create a virtual one.  If an individual quota doesn't exist, then create a virtual one from the metadata.  If some old quotas exist, then delete them!
=> Auto-Generate Quotas

README.md, charts/identity/Chart.yaml, charts/identity/templates/identity/deployment.yaml, charts/identity/values.yaml, pkg/middleware/authorization/authinfo.go, pkg/middleware/openapi/local/authorizer.go, pkg/rbac/rbac.go
Having these are regular users with groups and organizations is just wrong when what we really want is just a map from CN to role ID.
=> Migrate System Accounts

charts/identity/Chart.yaml, pkg/oauth2/oauth2.go
Ensure refresh tokens check the client ID and secret, and that the token is bound to that client.
=> OpenID Connect Conformance Part 9

charts/identity/Chart.yaml, pkg/middleware/openapi/local/authorizer.go
When building the userinfo in the local middleware we should check for scopes before derefencing.
=> Fix Segmentation Fault

charts/identity/Chart.yaml, charts/identity/crds/identity.unikorn-cloud.org_users.yaml, pkg/apis/unikorn/v1alpha1/types.go, pkg/oauth2/oauth2.go, pkg/oauth2/tokens.go
Add a unique ID to the authorization code, when we create a new session from the code associate the tokens with this.  If the code is potentially reused because it's not in the cache, revoke any tokens associated with that code ID.
=> Revoke Tokens on Code Reuse

charts/identity/Chart.yaml, pkg/oauth2/oauth2.go
3rd party onboarding relies on a user being able to login in order to extract their identity information and make organizations etc. on their behalf.  Sadly in issuing tokens, we need to add them to a user record in order to ensure single-use and revocation, which obviously doesn't tally with the original intention of OIDC, so hack around this.
=> Fix Userless Login

charts/identity/Chart.yaml, pkg/oauth2/oauth2.go
Just noticed the auditing is driven off subject, not email, which we may want to switcheroo in the future as alluded to in a bunch of comments.
=> Set Onboarding Subject

charts/identity/Chart.yaml, pkg/oauth2/oauth2.go, pkg/oauth2/oauth2_test.go
The exfiltration of a token can lead to multiple accounts being created and impersonation.  Limit the token to a single use and add a cache timeout to expire the token.
=> Add Account Creation Token Single Use

pkg/cmd/create/create.go, pkg/cmd/create/create_group.go, pkg/cmd/create/create_organization.go, pkg/cmd/create/create_user.go, pkg/cmd/get/get.go, pkg/cmd/get/get_user.go
Make following the links easier by doing it for you and outputting as a nice table.  This allows targetted filtering based on email or organization name for ease of support.  It also allows consistency checking across the whole estate as a sanity check.
=> Expand Kubectl Tooling

charts/identity/templates/_helpers.tpl, charts/identity/templates/identity/deployment.yaml, charts/identity/templates/oauth2client-controller/deployment.yaml, charts/identity/templates/organization-controller/deployment.yaml, charts/identity/templates/project-controller/deployment.yaml, charts/identity/values.yaml
Allow all services to have their resource allocations modified.  This mostly keeps things as they were, but only specifies limits not for guaranteed QoS scheduling.  The identity server has been expanded by 10x as memory utilization does tend to increase quickly when placed on the public internet!  The long term solution to growing numbers of resources and cache sizes is probably an external database, however that breaks the whole cascading cleanup thing when using namespaces...
=> Add Tweakable Resource Limits

.github/workflows/release.yaml
Use the super glob to ignore branch pushed with a / in them to avoid running spurious release jobs when dependency-bot does what it does.
=> Fix Release Action

charts/identity/crds/identity.unikorn-cloud.org_oauth2providers.yaml, charts/identity/values.yaml, pkg/apis/unikorn/v1alpha1/types.go, pkg/oauth2/common/authorization_code.go, pkg/oauth2/oauth2.go, pkg/oauth2/oidc/authorization_code.go, pkg/oauth2/providers/github/provider.go, pkg/oauth2/providers/google/provider.go, pkg/oauth2/providers/interfaces.go, pkg/oauth2/providers/microsoft/provider.go, pkg/oauth2/providers/null.go, pkg/oauth2/types/types.go
Allows the clinet ID and secret to be read from a secret, for example provided by external secrets operator.  Most of this is just tweaking the interfaces to propagate the clients to where they are needed, then just using literals or the secret.  Spotted a few library calls that can replace some exsting configuration, and where we were specifiying things that are implictly added.  Also fixed a typo in the API, so that needs calling out.
Fixes #279.
=> Allow OAuth2 Secrets from Secrets

pkg/handler/allocations/client.go
The object metadata interface updated to be more flexible, but as a result the old parameters (when nil) are still valid as callbacks, which results in a null pointer dereference.  Remove these nulls.  I have grepped everything, so this is definitely the last!!
=> Fix Allocation Updates

go.mod, go.sum, pkg/client/tokenissuer.go, pkg/constants/constants.go, pkg/controllers/oauth2client/manager.go, pkg/controllers/organization/manager.go, pkg/controllers/project/manager.go
THis updates the core library to pick up shared service descriptor types that can be used to simplify log intitialization and providing metadata to tracing calls.
=> Use Service Descriptors
