nscaledev/uni-identity

- charts/identity/Chart.yaml
- pkg/middleware/cors/cors.go
Didn't read the documentation!  Only one can be returned.
> Fix Access-Control-Allow-Origin

- charts/identity/Chart.yaml
- pkg/oauth2/federated.go
This provides a short cut to re-login on token expiry.
> Support OIDC login_hint

- charts/identity/Chart.yaml
- go.mod
- go.sum
- pkg/authorization/authenticator.go
- pkg/handler/handler.go
- pkg/middleware/openapi/local/authorizer.go
- pkg/oauth2/federated.go
- pkg/rbac/rbac.go
Also optimizes RBAC calculation.
> Use RBAC Core

- charts/identity/Chart.yaml
Messed up the actions permissions so we have to start again!
> Version v0.2.3

- pkg/oauth2/accesstoken.go
- pkg/oauth2/federated.go
Makes for better UX if you can just address someone by their given name.
> Make Full OIDC Info Available

- pkg/jose/jwe.go
- pkg/jose/jwe_test.go
Create some BDD style tests to protect the functionality of token issuance and make the code do what it should.
> Get Verification Working with Rotation

- charts/identity/Chart.yaml
A (too) large release, with the highlights:
* Support for embedded provider access tokens to facilitate groups access.
* Support for refresh tokens to get a new access token when the previous one expires.
* This also enables offline use of tokens with CLI clients.
* TLS signing key rotation support.
* Some API changes to enable project group management.
> Version v0.2.4

- charts/identity/Chart.yaml
Highlights:
* Organization API improvments
* OAuth2 API additions
> Version v0.2.5

- pkg/oauth2/oauth2.go
It's possible that the access token has expired, but so has the refresh token, and that spits out a totally crap error.  This is a speculative fix so I know it's in place on Friday when it will trigger again!
Fixes #63.
> Fix Token Expiry

- charts/identity/Chart.yaml
- go.mod
- go.sum
- pkg/authorization/authorizer.go
- pkg/middleware/authorizer/authorizer.go
Why I thought it was a good idea to live in core I'll never know, the bonus here is that we can share the same config flags.
> Move RBAC Authorizer Here

- charts/identity/Chart.yaml
- charts/identity/templates/_helpers.tpl
- charts/identity/templates/identity/deployment.yaml
- charts/identity/templates/identity/ingress.yaml
- charts/identity/templates/oauth2client.yaml
- charts/identity/templates/oauth2provider.yaml
- charts/identity/values.yaml
Pick a select few values and replace with templates that can get their value from a global.
> Improve Helm

- charts/identity/Chart.yaml
- pkg/handler/groups/client.go
Remove the deleted group from any projects that reference it.
Fixes #90
> Cascade Group Deletion

- charts/identity/Chart.yaml
- charts/identity/values.yaml
I consider this necessary for debug and support!
> Add Super Admin Quota Rights

- charts/identity/Chart.yaml
- charts/identity/templates/identity/deployment.yaml
- charts/identity/templates/organization-controller/deployment.yaml
- charts/identity/templates/project-controller/deployment.yaml
- go.mod
- go.sum
Nothing is affected by this, just switching to common libraries now to set precedent.
> Update Core Library

- charts/identity/Chart.yaml
- charts/identity/values.yaml
Physical networks are now just networks, update RBAC to reflect this.
> Update Network RBAC

- pkg/handler/serviceaccounts/client.go
We need to remove any reference to a service account on deletion, so if it's recreated it doesn't instantly get privilege escallation.  Plus it keeps things nice and tidy.
> Cascading Service Account Deletion

- charts/identity/Chart.yaml
- pkg/oauth2/oauth2.go
The whole loging hint stuff is from a bygone era and is irellevant now and just causes bugs.
> Remove Login Complexity

- charts/identity/crds/identity.unikorn-cloud.org_oauth2providers.yaml
- charts/identity/templates/oauth2provider.yaml
- pkg/apis/unikorn/v1alpha1/types.go
- pkg/apis/unikorn/v1alpha1/zz_generated.deepcopy.go
- pkg/handler/handler.go
- pkg/handler/oauth2providers/client.go
- pkg/oauth2/oauth2.go
Primarily for a demo, because it looks cool, but also because I'm using a non-Google/Microsoft account, and as it happens GitHub acts as a great aggregator of email accounts.
> Add GitHub as a Provider

- README.md
- charts/identity/Chart.yaml
- pkg/oauth2/oidc/authorization_code.go
Restore the retry hack for when restarting your laptop for make sanity.
> Fix Readme and OIDC Annoyance

- charts/identity/values.yaml
- pkg/handler/roles/client.go
Remove protected groups from those that are exported by the API, remove a bunch of obsolete permissions from the roles.
> Couple Small FIxes

- charts/identity/Chart.yaml
- pkg/handler/users/client.go
Handle non-API data preservation across updates.  It would *really* be something if this could be automated...
> Fix User Updates

- pkg/oauth2/oauth2.go
Return state to the client on a redirecting error, make PKCE optional and give it a default method.
> OpenID Connect Conformance Part 3

- charts/identity/Chart.yaml
- pkg/oauth2/oauth2.go
Make the client_secret and code_verifier POST options optional.
> OpenID Connect Conformance Part 5

- charts/identity/Chart.yaml
- pkg/oauth2/oauth2.go
Finally make basic client authentication work...
> OpenID Connect Conformance Part 6

- charts/identity/Chart.yaml
- pkg/handler/users/client.go
- pkg/oauth2/oauth2.go
Was hurried to push out a RC without doing a full test, this rectifies this!
> Fix User Creation

- charts/identity/crds/identity.unikorn-cloud.org_users.yaml
- pkg/apis/unikorn/v1alpha1/types.go
- pkg/apis/unikorn/v1alpha1/zz_generated.deepcopy.go
- pkg/handler/users/client.go
This used to be set by RBAC, but now we can do it based on the last active authentication.
> Fix Last Active

- README.md
You know when you can feel a question coming and need to point them at the docs...
> Preemptive Documentation Update

- charts/identity/templates/identity/deployment.yaml
- charts/identity/values.yaml
- pkg/oauth2/oauth2.go
Add in some late-to-the-party requests to improve the interface and complete the specification.
> Add Onboarding Tweaks

- pkg/handler/serviceaccounts/client.go
- pkg/middleware/openapi/local/authorizer.go
- pkg/oauth2/oauth2.go
- pkg/oauth2/oauth2_test.go
- pkg/oauth2/tokens.go
THis was getting fragmented and hard to grok, thus leading to bugs and causing inefficiencies.  Improve this!
> Refactor Tokens

- go.mod
- go.sum
Forgot to pick up the Core library!
> Version v1.2.0 (Again)
